services:
  # 1. Die relationale PostgreSQL-Datenbank
  db:
    image: postgres:15-alpine
    container_name: todo_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=catalog_db
    ports:
      - "5432:5432"

  # 2. Das C# Backend (REST-API)
  catalog-api:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: todo_api
    working_dir: /app
    volumes:
      - ./Catalog.API:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=catalog_db;Username=postgres;Password=secret
    ports:
      - "5001:80"
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0"]
    depends_on:
      - db

  # 3. Das ASP.NET Core MVC Frontend
  web-frontend:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: todo_mvc
    working_dir: /app
    volumes:
      - ./Web.Frontend:/app
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - BackendUrl=http://catalog-api:80
    ports:
      - "5000:80"
    command: ["dotnet", "watch", "run", "--urls", "http://0.0.0"]
    depends_on:
      - catalog-api

